### PR TITLE
do not overwrite existing git hooks

### PR DESCRIPTION
**Pull request by listefano**
## Description

This PR add the functionality described in issue #7.

I added the delimiter "# LARAVEL GIT HOOKS BEGIN #" and "# LARAVEL GIT HOOKS END #"

## How has this been tested?

I used composer to symlink to local repository to a new Laravel project and tested the functionality inside this new project. 

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by mr-feek — CHANGES_REQUESTED** [review]
Hi stefan,

First off, thank you!! 

If you have the time, would you mind making a few additions to this PR?

1) move the `LARAVEL GIT HOOKS BEGIN` and `LARAVEL GIT HOOKS END` delimiters to constants in this file, or to a trait? This will help share code with your other PR #20 

2) Use laravel's `Filesystem` https://laravel.com/docs/5.5/filesystem#the-local-driver instead of `file_get_contents` and `file_put_contents`. This will allow us to mock out the file system and unit test this PR (which I would like to do).

3) And finally, some test cases.

- given that a user has their own git hooks, ensure that laravel git hooks are appended and do not replace the existing git hooks
- given that a user does not have their own git hooks, ensure that laravel git hooks are appended.
- given that a user has custom git hooks and laravel git hooks already installed, the previous laravel git hooks replace the existing ones.

If you aren't able to make these changes, I can branch off of this PR and work on it a bit.

**Comment by listefano** [comment]
Hey, 

I could do these changes.

**Comment by listefano** [comment]
Hey @mr-feek,

I now added tests and also moved the delimiters to an trait.

**Comment by mr-feek** [comment]
👏  thanks!

**Pull request merged**
